locator= { 'account': 'accountSelect',  
        'acc-select': 'accountSelect',
        'acc_submit': '/html/body/div/div/div[2]/div/div[2]/div/div/form/button', 
        'Add_customer': "/html/body/div/div/div[2]/div/div[1]/button[1]", 
        'amount': "/html/body/div/div/div[2]/div/div[4]/div/form/div/input", 
        'back':"/html/body/div/div/div[2]/div/div[1]/button[1]",
        'curr_id': "currency", 
        'customer': '/html/body/div/div/div[2]/div/div[1]/button[3]', 
        'customer_login': '/html/body/div/div/div[2]/div/div[1]/div[1]/button', 
        'cust_submit': "/html/body/div/div/div[2]/div/div[2]/div/div/form/button", 
        'cust_table': "/html/body/div/div/div[2]/div/div[2]/div", 
        'delete': "/html/body/div/div/div[2]/div/div[2]/div/div/table/tbody/tr/td[5]/button", 
        'deposit': "/html/body/div/div/div[2]/div/div[3]/button[2]", 
        'deposit-success': '/html/body/div/div/div[2]/div/div[4]/div/span', 
        'deposit/withdrawl': "/html/body/div/div/div[2]/div/div[4]/div/form/button", 
        'details': '/html/body/div/div/div[2]/div/div[2]', 
        'dropdown_id': "userSelect", 
        'f_name': "/html/body/div/div/div[2]/div/div[2]/div/div/form/div[1]/input", 
        'home': '/html/body/div/div/div[1]/button[1]', 
        'login': "/html/body/div/div/div[2]/div/form/button", 
        'logout': '/html/body/div/div/div[1]/button[2]', 
        'l_name': "/html/body/div/div/div[2]/div/div[2]/div/div/form/div[2]/input", 
        'Manager': "/html/body/div/div/div[2]/div/div[1]/div[2]/button", 
        'next_page': "(//button[normalize-space()='>'])[1]",
        'open_acc': '/html/body/div/div/div[2]/div/div[1]/button[2]', 
        'post_code': "/html/body/div/div/div[2]/div/div[2]/div/div/form/div[3]/input", 
        'reset': '/html/body/div/div/div[2]/div/div[1]/button[2]', 
        'search': "/html/body/div/div/div[2]/div/div[2]/div/form/div/div/input", 
        'success': '/html/body/div/div/div[2]/div/div[1]/strong', 
        'transaction': "/html/body/div/div/div[2]/div/div[3]/button[1]", 
        'transaction-table': "/html/body/div/div/div[2]/div/div[2]/table", 
        'url_xpath': "mainHeading",
        'withdrawl': "/html/body/div/div/div[2]/div/div[3]/button[3]", 
        'withdrawl-success': '/html/body/div/div/div[2]/div/div[4]/div/span',
        'your-name':'/html/body/div/div/div[2]/div/form/div/label'
    }
